const LP = require('./VkAPI/LongPollServer')
const methodsManager = require('./VkAPI/methodsManager')
const socketIO = require('./Socket.IO/socket')
const WebSocketMessageHandler = require('./WebSocketMessageHandler')
LP.start()